Feat add tests
VlaPol/TMS_leson_28 pull request #1
Opened 2023-04-20 20:21 UTC by VlaPol

2023-04-26 19:09 UTC, oleg-grigorijan requested changes

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +    }
Это зачем?

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +        assertEquals(false, StringUtils.isBlank(inputArray));
Можно короче с assertFalse

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +        assertEquals(true, StringUtils.isBlank(inputArray));
Можно короче с assertTrue

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +        inputArray = new char[]{};
Довольно непоследовательно используешь `@BeforeEach`. Если уже и хочешь переиспользовать `new char[]{'h','e','l',' ', 'w'}`, то просто вынеси в константу

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +    void shouldReturnFalseIfMainStringsLengthIsZero() {
Скорее, если первая строка короче второй

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
isBlank: не хватает теста для строки из пробельных символов
isRussian: можно было бы проверить отдельно строчные, заглавные русские символы, ё, пустая строка

2023-04-26 19:09 UTC, grigo-oleg commented on src/test/java/by/tms/utils/StringUtilsTest.java
Автоформатирование

2023-04-27 16:05 UTC, VlaPol commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +    }
), забыл удалить, это автосгенерированные тесты на класс . убрал

2023-04-27 16:07 UTC, VlaPol commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +        assertEquals(false, StringUtils.isBlank(inputArray));
согласен, исправил

2023-04-27 16:09 UTC, VlaPol commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +        assertEquals(true, StringUtils.isBlank(inputArray));
согласен, исправил

2023-04-27 16:11 UTC, VlaPol commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +        inputArray = new char[]{};
исправил

2023-04-27 16:18 UTC, VlaPol commented on src/test/java/by/tms/utils/StringUtilsTest.java
сделал

2023-04-27 16:20 UTC, VlaPol commented on src/test/java/by/tms/utils/StringUtilsTest.java
> +    void shouldReturnFalseIfMainStringsLengthIsZero() {
ну да, неочень корректно назвал

2023-05-12 16:25 UTC, merged